In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('final_csv/bussinessweekly.csv')

In [2]:
df

,URL,Date,Title,Author,Content
0,https://wealth.businessweekly.com.tw/GArticle....,2020/07/20,國安基金不退場，股市會過熱嗎？,陳唯泰,意外國安基金不退場話說國安基金暫時沒有打算要退場計畫要護盤到疫情結束這個結論真的太嚇人了因為...
1,https://wealth.businessweekly.com.tw/GArticle....,2020/07/20,台積電去美國不夠，還要去日本？讀賣新聞：日府擬邀合建晶片廠,黃嘉洵編譯／經濟日報,讀賣新聞19日報導日本政府正打算邀請台積電或全球其他晶片業者與國內晶片設備供應商攜手建立先進...
2,https://wealth.businessweekly.com.tw/GArticle....,2020/07/20,華為衝擊已過＋5G需求加持，外資看好穩懋股價上看400元,Atkinson,亞系外資在最新研究報告中指出功率放大器及砷化鎵代工大廠穩懋3105在當前股價已大致反映對華為...
3,https://wealth.businessweekly.com.tw/GArticle....,2020/07/17,台股萬點以上就是貴？從「1指標」看，找出相對高低點,Charlotte夏綠蒂,2020年3月股災全球股市重挫新冠肺炎首宗感染個案發病時間是2019年12月1日後來相關人員...
4,https://wealth.businessweekly.com.tw/GArticle....,2020/07/17,金融海嘯大賠出場，老婆抱著他一起哭，存股達人孫悟天老婆真心話：感謝那次慘賠的經驗...,孫太,夫妻因為投資理念不同產生不愉快該怎麼辦日前陸續遇到一些讀者詢問因為投資理念不同導致跟另一半產...
...,...,...,...,...,...
1532,https://wealth.businessweekly.com.tw/GArticle....,2012/09/06,超愛錢的大學生 怎麼創業才會成功？,李柏鋒,Q您好我是一個大學生對金錢充滿熱情希望畢業後可以創業想要累積多一點的創業基金您覺得大學生投資...
1533,https://wealth.businessweekly.com.tw/GArticle....,2012/08/30,當中華電信也不是定存股時...,李柏鋒,Q最近有一筆閒錢因為定存利率實在很低所以寧願冒一點風險投資定存股來獲取比較高的報酬這樣可行嗎...
1534,https://wealth.businessweekly.com.tw/GArticle....,2012/08/16,不調薪，還是能致富的3種方法,李柏鋒,Q我的薪水已經五年沒調整支出已經省到被認為是最小氣的代表了收入我又不知道怎麼樣才能增加我該怎...
1535,https://wealth.businessweekly.com.tw/GArticle....,2012/06/29,怎麼樣才能不上班也有錢？,李柏鋒,Q到底什麼是財務自由A自從羅伯特清崎的富爸爸窮爸爸系列理財書籍在台灣上市以後許多人的人生終極...
1536,https://wealth.businessweekly.com.tw/GArticle....,2012/04/12,當死薪水碰上通膨怎麼辦？,Buffettism (李柏鋒),油電雙漲已經是無法改變的事實隨之而來的通貨膨脹物價上漲也是預料中事我們該怎麼理財才能打敗通膨...

In [3]:
from ckiptagger import data_utils, construct_dictionary, WS, POS, NER
ws = WS("./data")
pos = POS("./data")
ner = NER("./data")

In [ ]:
# Load stock_dict
stock_dict = np.load('stock_dict.npy',allow_pickle=True).item()

In [13]:
df.dropna(subset=['Date','Content'],inplace=True)
df.shape

(1535, 5)

In [14]:
# 將文章內容進行斷詞
word_segment = ws(
    df['Content']
    # recommend_dictionary = dictionary1, # words in this dictionary are encouraged
    # coerce_dictionary = dictionary2, # words in this dictionary are forced
)

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
# 將每篇文章斷詞的list合併成以空格分隔的字串
cut_corpus = []
for i in word_segment:
    cut_corpus.append(' '.join(i))

# 計算詞頻    
text_cv = CountVectorizer()

td_matrix = text_cv.fit_transform(cut_corpus)

print(td_matrix.shape)

#print(text_cv.vocabulary_.keys())

(1535, 43068)

In [34]:
# 將詞頻矩陣變成Dataframe
td_df = pd.DataFrame(td_matrix.toarray(), columns=text_cv.get_feature_names())

In [38]:
td_df.shape

(1535, 43068)

In [39]:
# 將詞頻的Dataframe存起來
td_df.to_csv('./test_data/td.csv', index=False)

In [40]:
# 讀取詞頻Dataframe的csv檔
import pandas as pd
td_df = pd.read_csv('./test_data/td.csv')

In [50]:
# Dataframe轉numpy array
td_matrix = td_df.values

In [51]:
td_matrix.shape

(1535, 43068)

In [52]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

# 計算tf-idf矩陣
tfidf = TfidfTransformer()

tfidf_matrix = tfidf.fit_transform(td_matrix)

In [58]:
import pandas as pd
df = pd.DataFrame(tfidf_matrix.toarray(), columns=td_df.columns)

In [59]:
df

,00000000000000002,000063,0001,0001425,0003,0003215375,0005,001,00120,001一年,...,龍頭元,龍頭廠,龍頭性,龍頭級,龍頭股,龍飛鳳舞,龐大,龐氏,龐然大物,龜山
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.12418,0.0,0.0,0.0
1531,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1532,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1533,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1534,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0

In [60]:
# 存tf-idf
df.to_csv('./test_data/tdidf.csv', index=False)

In [ ]:
# 進行文件分類
# X可以為tf或tf-idf
# tf需要先刪除停用字(stop words)  tf-idf可直接用
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer(stop_words='english',
                        max_df=.1,
                        max_features=5000)
X = count.fit_transform(df['review'].values)

In [19]:
import pandas as pd
tfidf = pd.read_csv('./test_data/tdidf.csv')

In [20]:
tfidf

,00000000000000002,000063,0001,0001425,0003,0003215375,0005,001,00120,001一年,...,龍頭元,龍頭廠,龍頭性,龍頭級,龍頭股,龍飛鳳舞,龐大,龐氏,龐然大物,龜山
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.12418,0.0,0.0,0.0
1531,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1532,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1533,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1534,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0

In [21]:
import re
remove_list=[]
for colname in tfidf.columns:
    if re.match(r'[0-9a-z]',colname):
        remove_list.append(colname)

In [24]:
remove_list[-20]

'z5'

In [23]:
# 保留有用的詞
remove_list.remove('5g')
remove_list.remove('iphone')
remove_list.remove('ipad')
#remove_list.remove('vr')

In [25]:
len(remove_list)

9544

In [26]:
tfidf.drop(columns=remove_list,inplace=True)

In [27]:
X = tfidf.values
X.shape

(1535, 33524)

In [47]:
from sklearn.decomposition import LatentDirichletAllocation
# n_components代表分成幾個主題
lda = LatentDirichletAllocation(n_components=10,learning_method='batch',n_jobs=-1)
X_topics = lda.fit_transform(X)

In [31]:
lda.components_.shape

(5, 33524)

In [51]:
# 印出每個主題前幾重要的關鍵字
# 看起來還是需要刪除停用字
# 或者只是商周不適合分類
n_top_words = 20
feature_names = tfidf.columns

for topic_idx, topic in enumerate(lda.components_):
    print("Topic %d:" % (topic_idx + 1))
    print(" ".join([feature_names[i]
                    for i in topic.argsort()\
                        [:-n_top_words - 1:-1]]))

Topic 1:
廢除 佳格 楊忠憲 歐尼爾 台中幫 丹尼爾 麥大 藥局 捕手 大樹 手表 抱緊股 紙廠 一面 分離 公路車 忠孝 老伯伯 芭樂 階段性
Topic 2:
薪酬 張松允 愚公 全球化 宏碁 民股 偏方 戴勝益 散裝 艾倫 觸覺 購物金 張簡亦杰 賴正鎰 試算表 友華 水滴 子帳戶 奶粉 天線
Topic 3:
悟天 俄羅斯 年線 走強 曾銘宗 熱錢 乃至 空單 日股 救市 終場 原油 平盤 負利率 選舉 熊市 成交值 收益債 摩根 股匯市
Topic 4:
鋼價 陳族元 華映 隱形眼鏡 捕手 任天堂 凌華 時薪 縮表 綠能 楊忠憲 保理 落袋 大疆 慶富 弘塑 再生 芭樂 謝克爾 指南
Topic 5:
聯強 獲股感 知識庫 逐筆 出借 公股 原文 樂陞 轉載 授權 中鼎 麵包 財貨 耐久性 漢微科 大哥 海運 金融家 償債 直升機
Topic 6:
聯華 華票 華研 藝人 迅銷 遠業 音樂 空令 麵粉 普萊斯 蝦皮 滿分 唱片 阿姨 國民黨團 味全 王美花 解盤 流浪 耐吉
Topic 7:
康達智 力晶 特斯拉 陳韋廷 瓦城 購屋 頭部 端午節 內斂型 造紙 口罩 台銀 抵減 十方 草莓族 楊宗憲 鋰電池 黃崇仁 固網 紙漿
Topic 8:
楊忠憲 威剛 指數化 漢科 種出 一零四 台汽電 捕手 巨路 台電 漢唐 老人 重質 下流 宏全 芭樂 諾基亞 小胖 牛奶 焊接
Topic 9:
投資 股票 公司 股價 市場 可以 台股 股利 台灣 股市 獲利 營收 如果 因為 投資人 指數 自己 我們 現金 可能
Topic 10:
威盛 亞銳士 示警 芭樂 張偉明 三豐 突進 醫材 物美 價廉 優化組 挑股 創業家 合晶 核對 張善政 大勢 五哥 出生率 耳機

In [36]:
import pandas as pd
import numpy as np
df = pd.read_csv('final_csv/bussinessweekly.csv')

In [43]:
df.dropna(subset=['Date','Content'],inplace=True)

In [62]:
# 印出該主題前幾篇文章
# 爬蟲的資料有些問題需要修正
# topic 8
topic = X_topics[:, 7].argsort()[::-1]

for iter_idx, article_idx in enumerate(topic[:10]):
    print('\nArticle #%d:' % (iter_idx + 1))
    print(df['Author'][article_idx])
    print(df['Date'][article_idx])
    print(df['Content'][article_idx], '...')

Article #1:
2017.03.24
瀏覽數：13503
圖片來源dreamstime股票市場上每個人想的不外乎一件事獲利因此當所持有的股票下跌甚至帳面出現虧損時心中所想的並不是所投資的公司是否在財務上出現了狀況或是業績不理想這些公司基本面的東西而是想這股票什麼時候漲回來逢低我該怎麼加碼攤平至於停損這兩個字彷彿不在大多數投資人的操作策略之中為什麼這樣因為人性使然就許多投資人而言包括我亦然停損意味著帳面虧損的實現停損意味著自己當初的看法錯誤所以停損的行為等同於投資失敗之意但可笑的是堅持不停損的結果往往是抱越久跌越深攤越平以我為例當初買進一檔面板股號稱投入當時最夯的觸控面板產業原想買個一張試水溫卻手眼神經失調掛233元變成買23張沒錯這是第一個烏龍錯誤好不容易湊了錢入集保戶頭當時未開信用戶無法當沖心想既然都買了就看它會不會漲結果股價像滑樓梯般從233元到最低6元而我終於在9到10元時才認賠殺出帳面虧損將近30萬豈是慘字了得散戶思維停損等於承認自己犯錯繼續攤平等待股價回來存股思維1選到錯誤的股票公司虧損股價高於價值不論價格為何都必須殺出留得青山在不怕沒柴燒2不是所有的股票都可以攤平虧損或配不出現金的公司不可以攤平操作策略可換成穩定的配息股或高殖利率股即使帳面虧損仍保有每年領息的價值填不填息要看3到5年不要只看單一年度Ex我將抽出的資金換買興農1712目前股價漲了兩成本文撰於2012年6月今年度可以領到1萬多元的股息附表溫國信先生賣股檢核表小樂文字修正版 ...

Article #2:
2016.05.11
瀏覽數：55437
圖片來源dreamstime每四年一次的總統520就職演說一直是投資人的夢魘和魔咒有時是期待新總統對經濟有前瞻樂觀的談話有時是擔心談話內容激怒對岸領導人所以總是讓大家既期待又怕受傷害小英總統即將上任演說內容動見觀瞻動輒得咎因此大家乾脆退場觀望指數從今年最高點8840下跌近8不只吐光今年原有的漲幅甚至已經倒退嚕尤其是428至56短短6個交易日已回檔近400點都印證投資人的保守與恐慌如果小英總統演說承認九二共識保證隔天全部股票都漲停板如果高喊台灣獨立那就非全部躺平跌停鎖死不可了有可能是這兩個極端嗎我想機會趨近於零當一切照本宣科了無新意股市的不確定性自此消除就會回歸它該有的基本面了沒有人能判斷演講後的兩岸情勢只能猜測有人猜兩岸關係不致有大變化有人猜兩岸關係會更加嚴峻投資人相信前者推論就會偏多思考現在就趁低檔拼命買進若相信後者推論就會看壞後市不只現在不進場甚至還可能大舉放空台灣投資人對小英總統的演講內容嚴陣以待全球投資人則對美國聯準會升息與否屏息以對這都是考驗投資人判斷的時候判斷正確的人當然值得用高獲利來獎勵判斷國內外政經情勢發展究竟是有利投資還是不利投資判斷個別公司未來的成長前景究竟是該買還是該賣判斷各項技術指標是現在買還是等幾天再買是現在賣還是等幾天再賣怎麼判斷呢先來聽聽電視那些專家怎麼說結果有多也有空有句話形容得非常貼切十個經濟學家有十一種看法因為有人會講得模稜兩可好像兩種看法都並存這時候你不是判斷國內外情勢或個別公司的情況你是要判斷自己相信哪個專家你買了股票就相信看多的專家你手上沒有股票或甚至放空股票就相信看空的專家對不對每個人做的決定都是因為相信自己的判斷是對的但究竟對或錯還是忐忑不安非常焦慮與其去做困難的判斷還不如去執行簡單的紀律紀律的依據就是很多投資人都相當熟悉的技術指標大盤日KD已來到10的相對低檔自高點回檔也快回到此波漲幅的0382之處都代表超賣嚴重具備了隨時要反彈的條件這時去買60元以下的台灣500050或20元左右的高股息0056吧萬一真的套牢前者近年平均配2元股息殖利率超過3後者近年平均配1元股息殖利率更接近5有啥好怕520之前當然可以買進這兩檔股票啊請千萬別說跌到7000點或50元以下才要買因為真有這麼一天市場上一定人心惶惶你或許還不敢買呢 ...

Article #3:
編輯部
2020/05/05
K線捕手楊忠憲最近真是旺旺旺除了抓到金像電2368這檔將近40漲幅的飆股外4月20日首度解析晶電2448到今天1617矽統2636則上漲1353奇鋐3017上漲1147恭禧有抓到飆股的同學想跟著楊忠憲老師抓飆股快上自學網K線求生指南來看看楊忠憲老師上週有提醒大家多方已經上漲到壓力區有聽老師的話減碼的同學今天也要一起恭禧了本週大盤怎麼看快聽楊忠憲老師說分明更多Smart智富投資影片 ...

Article #4:
2017.01.18
瀏覽數：14445
圖片來源dreamstime公司本身是虧損的那無形資產根本就是個屁昶洧4529無形資產是資本額的55倍財報中總是會有很多眉眉角角的東西例如金融業的備供出售的金融資產的估值電子業的存貨漲價跌價以及各行各業的應收帳款品質這些雖然都是小細節但是仍關乎一家公司是否能夠長期持有或者判斷是否值得買進的依據今天我們來介紹去年7月份編按本文撰於2016年4月大盤空頭時我選擇偏空看待宏碁2353的重要原因無形資產一常見可辨認性無形資產1專利權2著作權3商標權4電腦軟體5許可權經銷權6發展中之無形資產7刊頭及出版品名稱8處方配方模型設計及原型二不具可辨認性無形資產1商譽企業合併而取得的無形資產商譽商譽不適用財務會計準則公報第三十七號的規範而是依照財務會計準則公報第二十五號企業合併購買法之會計處理予以處理而宏碁就是在第二項中花的錢最多但是沒有發揮綜效的企業以下是宏碁2353的資產負債表總共4大項資產最多1現金2應收帳款3存貨4無形資產宏碁2353的無形資產占了整體資產的15這應該是上市公司中相對比較高的無形資產的市值266億若論總金額的話宏碁的無形資產市值應該是上市公司中最高的華碩2357的無形資產1市值近20億兩相比較之下我們很清楚的可以知道宏碁2353在這方面真的沒有華碩來得優我們再看看另外一家無形資產也相對大的宏達電2498在去年第四季報告中無形資產比重4市值55億元這比例也比宏碁2353來得少很多通常一家公司無形資產越少越好大立光的比例跟金額就非常低就用上面得到的資料做比較無形資產比例宏碁2353宏達電2498華碩2357無形資產總市值宏碁2353宏達電2498華碩2357因為宏碁2353無形資產主要來源是來自於購併以下是相關新聞我們發現宏碁2353不斷的透過購併想要提升公司本身的競爭力但是就結果論宏碁在這方面的購併卻沒有達到預期的效果因此龐大的無形資產就成為宏碁在財報中的未爆彈因為會不定時的認列減損無形資產本身是用錢去購買的如果要發揮無形資產的效益那公司本身一定要賺錢如果公司本身是虧損的那無形資產根本就是個屁也代表公司的政策買了一大堆公司卻無法讓公司營運好轉這是治理上的錯誤結論1無形資產一定要搭配公司獲利不然只是空談2因為無形資產認列減損的時機不是我們可以控制的但是它可以被公司派控制會短暫影響股價我們需要注意3承上面結論如果我們要挑選定存好股一定要避開無形資產比例高的個股這樣我們存股才會相對安心 ...

Article #5:
2017.05.05
瀏覽數：158549
圖片來源dreamstime5年前我跟太太商議每個月各自從戶頭當中提領10000元存入共同帳戶作為家庭的緊急預備金之用這一筆每個月的緊急預備金大約占我們兩人薪水的15說實在的扣除掉每月家庭的一些開支要存下各自薪水的15其實不是挺容易的事但我們仍堅持存了5年今天是我們存滿5年的到期日編按本文撰於2015年7月打開帳戶一看也已累積了一筆不算少的家庭預備金雖然這一筆預備金在許多人眼裡不算豐厚但走過這5個年頭看到我跟太太努力的成果心裡仍是有份感動再進一步想到我從5年前完全不懂投資理財到如今略懂的程度中間付出的心力其實真的不足為外人道也我想在這累積預備金的過程中我學到的最重要的兩件事就是堅持與紀律堅持才能讓資產不斷累積紀律才能遠離人性的弱點當我們知道自己追求的目標與方向在哪就應該一步一腳印地堅持到底即便過程中有再多的困難也不要放棄很多人為自己不學習理財投資找了許多藉口其實很多事情只要我們有心它並非是那麼困難的事情希望大家能從現在起為自己和家人努力充實理財和投資的知識朝著堅持與紀律的道路前進後記我跟太太說既然我們已經存到了一筆足夠的緊急預備金水位接下來每個月投入的資金其實可以用來存股票例如第一金等低價的金控股假設我們每個月存一張第一金那麼5年後我們就將擁有60張的股票而這60張的股票又會每年生出股子股孫給我們假使第一金的獲利能力仍舊不變每年仍能持續配發股息與股票股利那麼這樣一來就有機會創造高於定存數倍的報酬率5年前我定存現金5年後我定期存股票希望下一個10年我能擁有足夠的現金流讓我完成財務自由的夢想 ...

Article #6:
編輯部
2020/07/14
資金狂潮來了巨大9921旺矽6223士紙1903榮創3437永冠KY1589系統電5309鎧勝5264K線捕手楊忠憲上週私房股全面大漲你跟上幾檔本週要布局哪類型的股票比較有勝算快看影片分析更多Smart智富投資影片 ...

Article #7:
呂淑美
2016/06/01
台灣高鐵2633昨31日向證交所送件申請上市由於高鐵曾歷經營運風雨飄搖去年經過財務解決方案後才又有起死回生的契機昨天申請上市格外具有特殊意義證交所表示高鐵今年底可望掛牌交易高鐵送件申請上市消息傳出午盤過後在興櫃市場股價一度急拉至1586元最後以157元上漲109元作收成交張數逾2985張較前一天倍增據高鐵送件公開說明書中記載發行價格暫訂每股115元高鐵成立於民國87年5月11日目前全台共有11站營運行駛南港車站預計今年7月1日加入載客服務屆時總計為12個車站全線通車營運過去多年以來高鐵一直陷入慘澹經營狀態依高鐵公開說明書記載101年及102年每股各虧損016元及052元103年基本每股盈餘為139元追溯調整後去年2月由原獨立董事劉維琪接掌董座後104年展開財務解決方案進行高達390億元的減資彌補累計虧損高鐵目前公司實收資本額56053億元含私募300億元104年稅前純益18834億元稅後盈餘20823億元每股稅後盈餘EPS719元擬將配發065元現金股利證交所表示帶動高鐵104年大幅獲利主要是因執行高鐵財務解決方案在業外收入有73億元包括返還站區地上權折減回饋金利益226億元認列特別股補償金費用151億元及營業收入也認列興建營運合約法定優待票短收差額收入121億元證交所表示高鐵目前普通股資本額為260億餘元是近5年來僅次於102年申請上市的亞太電資本額328億元第2大資本額的公司上市是證交所推動大型企業上市的一個重要指標公司依高鐵初步規畫此次上市現金增資發行普通股2300萬股依一般市場承銷價格訂定方式參考市價法成本法現金流量折現法及近1個月興櫃市場平均成交價等方式推算每股暫定發行價格為115元預計募集資金總額2645億元證交所表示未來高鐵上市案將採競價拍賣及公開申購兩者並行的方式進行惟最後承銷價仍有待未來興櫃價格變動才能作最後確定工商時報 ...

Article #8:
陳苓
2016/08/09
智慧手機遊戲PokmonGO精靈寶可夢GO終於在台灣開放引發全民抓寶熱數據顯示PokmonGO全球上架的第一個月淨營收高達2億美元打破新高CNBCVentureBeatDigitalTrends報導應用軟體研究商SensorTower研究顯示PokmonGO在全球開放下載的第一個月蘋果AppStore和谷歌GooglePlay的淨營收高達2億美元刷新紀錄日本更是銷售暴增的一大助力遊戲7月22日在日本上架之後營收明顯上揚線圖見此和2014年的熱門手遊糖果傳奇CandyCrushSaga相比PokmonGO首月淨營收為糖果傳奇的七倍以上另外今年3月開放下載的另一熱門手遊部落衝突皇室戰爭ClashRoyale上架頭30天的營收也只有125億美元SensorTower指出PokmonGO刷新多項紀錄是全球最快下載1千萬次的手遊玩家平均每天花26分鐘玩此一遊戲另一機構AppAnnie7月表示PokmonGO平均每天賺進1000萬美元PokmonGO熱門民眾外出抓寶引發行動電源大熱賣研究機構NPD發現PokmonGO開放下載之前美國行動電源銷售年增率只有47月初遊戲在美國上架之後7月10日7月23日的兩週之間行動電源買氣年增101狂賣120萬個NPD消費科技業界分析主管BenArnold說PokmonGO需要用到定位動態感測擴增實境等功能相當耗電用戶購買行動電源確保有足夠電力能持續抓寶行動電源概念股包括昂寶KY4947致新8081松翰5471全漢3015雙鴻3324超眾6230等日本蘋果情報網站iPhoneMania4日報導蘋果執行長庫克TimCook在Twitter發文稱7月份AppStore銷售額創下史上新高紀錄且7月份支付給研發人員的金額也創下史上最高的500億美元庫克並未公開AppStore7月份的具體銷售額數字 ...

Article #9:
WIKI
2018/03/08
圖片來源photoaccom有華人在的地方就一定有補習教育的需求不管教育部怎麼修改制度希望減輕學生的壓力但幼兒到大學各種的補習教育只有愈來愈多的趨勢大家都想要贏在起跑點最後都輸在終點連我在美國矽谷的表哥每個月花在兩個子女的教育也能高達10幾萬台幣看來不是教育制度的問題只要華人父母心態不改補教永遠是個好生意近年陸續有補教公司三貝德卓越大地KY智基掛牌或借殼進入資本市場其中有一個共有的特色這些公司或多或少都推出了數位教學以前可能有場地時間的限制所以補習班會有區域性一旦運用了雲端教學這些限制都能打破全台灣可以同時有一萬名學生看呂捷直播教歷史最後補教業很可能走上大者恆大弱者被淘汰的狀況市場規模與發展在台灣每年補教的市場大約是15001700億由三個市場平分兒童到大學的補教外語的進修成人的就業與證照目前台灣數位教學的佔比大約是10鄰近國家南韓較早發展數位教學而且補習文化更勝台灣目前他們的數位學習佔比為30台灣應該還有不小的成長空間另外還有一個不小的市場家教因為是地下經濟所以沒有精準的產值統計有人力銀行統計約有一成七的上班族曾經或正在從事家教每個月大約有6000元的收入對於家教媒合這件事來說肯定是個值得做的生意像是英語學習網站TutorABC就算是個成功的媒合平台其他種類的家教媒合平台也肯定商機無限志光從創立到掛牌1979年志光補習班的創辦人林進榮拿著36萬元資本額於台南市成功路上開設了第一家志光補習班藉由不斷收購整併八二年以來陸續吃下了台南市政大補習班台中市學儒補習班台北市金榜補習班高雄市專辦醫藥護理的冠林補習班台北市專辦司法官律師考試的保成補習班與雙榜補習班等藉由全台併購完成全國皆有班系的通路數位相機起家的智基科技6294近幾年陸續引進志光之資金讓志光借殼掛牌轉型成為台股第一家補教業的上櫃公司營運內容已100來自相關業務目前在全台共有63個實體門市志光數位學院產業生態傳統的補教業生態鏈概略如下老師教材產品補習班通路學生消費者好的老師絕對是吸引學生來上課最重要的因素特別是名師因為沒辦法複製只要能找名師到自己的補習班教課就幾乎成了票房的保證超強的名師也要搭配有超強招生能力的補習班老師一天也就幾個小時能教課要如何在有限的時間內讓收入極大化就是補習班的責任像所有的產業一樣有些老師自己開補習班做到垂直整合像是陳立數學徐薇英文還有在高速公路開車很穩的高國華老師英文但開補習班就要會經營管理不是每個老師都行所以大部分都是各司其職老師負責教書補習班負責行政招生等等的事情同業比較目前專注在台灣市場並且已經上市櫃的補教公司有三貝德8489卓越2496智基6294概略做個比較如下教學數位化志光補習班的產品大概可分為幾個類型老師教室交授門市據點看影片DVD帶回家看家裡雲端看影片營收佔比因為公司沒揭露所以不清楚因為公職考試的科目種類繁多各科目很難在各縣市都湊滿足夠人數開課所以讓老師錄製一次教學影片再透過數位教學讓學生學習是非常好的商業模式比方離島的金門或澎湖的考生因為人口比例低很難湊足人數開課只要去志光在當地的據點看DVD一樣能達到學習效果在網路技術還不成熟的時代志光全國63個據點就是最佳的通路是非常重要的資產卻也是未來發展很大的包袱公司當然有看到未來雲端的發展也推出了雲端教學從雲端介紹影片就能看得出來網站似乎還停留在非常早期的技術登入的流程繁瑣也是很嚇人猜測雲端這部分的營收一定不多所以沒被公司特別看重以公司手上有的預算不是不能做好要不要做而已有一個商業上的例子曾經街頭巷尾都能看到的百視達Blockbuster門市在網飛Netflix雲端出現後從此銷聲匿跡百視達當然也有去發展線上影音最後還是輸給Netflix最終破產做實體生意與做網路生意的思維真的非常不同要非常小心是否有網路原生的公司來搶食雲端這塊大餅公職補教受景氣循環影響教育是非常剛性的需求因為機會成本與時間成本相當高年輕只有一次過了就回不去所以完全不能等在能力許可下要選擇最好的正常情況下升學補教不會有景氣因素公職補習教育的需求卻很特殊公職補教的需求與失業率成反向愈多人失業的時候就愈多人去報考公職反而是景氣比較好充分就業的時候生意會比較淡失業率愈高生意愈好是我單純從報考人數上的推論因為能看到的財務資料不夠多可以等失業率攀高的時候來驗證一下公司業績是否因此增加股市中把不受景氣影響的股票稱做防禦型股票或許這種景氣愈差生意愈好的股票可以稱作超牛防禦型股票跨入升學市場與旅遊市場智基主要的業務以公職為主近年跨入了旅遊市場與升學市場希望能帶動營收成長基本上這兩個市場競爭都非常激烈公司要跨入並不容易如果硬要說手上有客戶名單考取公職的學生名單或是有實體門市能做為通路也都不是很強的利基未來是否能貢獻獲利有待觀察除了開拓新的市場更重要的是把既有的公職補教市場護城河挖深一點另一間上櫃公司三貝德8489也有意圖進入公職這個市場單獨從數位化能力這點來看三貝德應該是勝智基如果未來的戰場在雲端智基似乎還沒準備好三貝德在上櫃業績發表會時評估大概三年內能做好準備切入公職這個市場智基如果沒辦法加強自己的優勢很可能就會面臨挑戰參考資料榮智基科技林進榮神祕補教大亨起底從藥廠小業務到借殼飆股大老闆如何在補教界擁有自己的一片天三貝德數位文創上櫃前業績發表會補教人生補教概念股討論區本文獲WIKI股票投資筆記授權轉載原文補教人生智基6294 ...

Article #10:
編輯部
2020/05/19
上週一我們直播的時候當天大盤上漲到最高1萬1039點K線捕手楊忠憲卻說多方上漲力道已竭盡的味道果然一整週多方上攻無力昨天5月18日收1萬740點回了將近300點楊忠憲老師上週解析的大學光3218這週漲了23中連貨5604也漲了10在大盤未升段還有哪些潛力股可以操作嗎更多Smart智富投資影片 ...