In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('final_csv/all_web.csv')

In [2]:
df

,URL,Date,Title,Author,Content,Website
0,https://wealth.businessweekly.com.tw/GArticle....,2020/07/20,國安基金不退場，股市會過熱嗎？,陳唯泰,意外國安基金不退場話說國安基金暫時沒有打算要退場計畫要護盤到疫情結束這個結論真的太嚇人了因為...,bussinessweekly
1,https://wealth.businessweekly.com.tw/GArticle....,2020/07/20,台積電去美國不夠，還要去日本？讀賣新聞：日府擬邀合建晶片廠,黃嘉洵編譯／經濟日報,讀賣新聞19日報導日本政府正打算邀請台積電或全球其他晶片業者與國內晶片設備供應商攜手建立先進...,bussinessweekly
2,https://wealth.businessweekly.com.tw/GArticle....,2020/07/20,華為衝擊已過＋5G需求加持，外資看好穩懋股價上看400元,Atkinson,亞系外資在最新研究報告中指出功率放大器及砷化鎵代工大廠穩懋3105在當前股價已大致反映對華為...,bussinessweekly
3,https://wealth.businessweekly.com.tw/GArticle....,2020/07/17,台股萬點以上就是貴？從「1指標」看，找出相對高低點,Charlotte夏綠蒂,2020年3月股災全球股市重挫新冠肺炎首宗感染個案發病時間是2019年12月1日後來相關人員...,bussinessweekly
4,https://wealth.businessweekly.com.tw/GArticle....,2020/07/17,金融海嘯大賠出場，老婆抱著他一起哭，存股達人孫悟天老婆真心話：感謝那次慘賠的經驗...,孫太,夫妻因為投資理念不同產生不愉快該怎麼辦日前陸續遇到一些讀者詢問因為投資理念不同導致跟另一半產...,bussinessweekly
...,...,...,...,...,...,...
852362,https://www.businesstoday.com.tw/article/categ...,1998/11/19,掃清地雷 好股出頭天 P.38,老謝,從國產汽車新巨群集團再到國揚集團主動宣布跳票之後面對企業危機不斷惡化擴大財政部終於在十一月十...,businesstoday
852363,https://www.businesstoday.com.tw/article/categ...,1998/11/19,丙種金主葬身股海 P.28,江柏宣,如果你原本是身價二十億元的富翁卻在短短幾天內就灰飛煙滅你還會想活嗎國產車國揚新巨群連續跳票風...,businesstoday
852364,https://www.businesstoday.com.tw/article/categ...,1998/11/12,炒手不死 跌勢不止 P.16,NaN,最近股市地雷股逐一引爆繼東隆五金羅傑建設央票宏票國產車新巨群等公司周轉不靈之後國揚集團董事長...,businesstoday
852365,https://www.businesstoday.com.tw/article/categ...,1998/11/12,一元買台「股票機」P.119,李立鑫,最近國內股票市場低迷公司老闆票子跳成一團投資大眾怕抱到地雷股紛紛走避不過和股市息息相關的股票...,businesstoday
852366,https://www.businesstoday.com.tw/article/categ...,1998/11/05,新巨群捅下大窟窿 P.22,江柏宣、吳芥之,羅傑建設新巨群集團中央票券原本是水幫於魚幫水的命運共同體羅傑與新巨群從中央票券取得數十億元的...,businesstoday

In [3]:
from ckiptagger import data_utils, construct_dictionary, WS, POS, NER
ws = WS("./data")
pos = POS("./data")
ner = NER("./data")

In [4]:
# Load stock_dict
stock_dict = np.load('stock_dict.npy',allow_pickle=True).item()

In [5]:
stock_dict = construct_dictionary(stock_dict)

In [8]:
word_segment = ws(
    df['Content'][480000:500000],
    recommend_dictionary = stock_dict # words in this dictionary are encouraged
    # coerce_dictionary = dictionary2, # words in this dictionary are forced
)

cut_corpus = []
for i in word_segment:
    cut_corpus.append(' '.join(i))

df2 = df.iloc[480000:500000,[0,1,2,3,5]]
df2['Words'] = cut_corpus
df2.to_csv('./words/words_480k_500k.csv', index=False)

In [9]:
df2

,URL,Date,Title,Author,Website,Words
480000,topicdetail.php?f=291&t=818406,2008/10/25,公司薪資戶問題？,orvkuykgii,mobile01,公司 搭配 的 銀行 有 特定 所以 每 去 一 家 新 公司 就 要 重新 開戶 一 次 ...
480001,topicdetail.php?f=291&t=783991,2008/09/24,[求助]我想買水餃股.....,Macibs,mobile01,對 股市 實在 沒有 時間 去 了 解看到 現在 水餃股 那麼多 決定 花筆 錢 來 給 他...
480002,topicdetail.php?f=291&t=816973,2008/10/24,"""限跌德政""到今天是吧...",武告頌,mobile01,我 下 星期 看 狀況 再 考慮 進場 吧 鴻海 一直 破底 快 跌到 十 年 以前 的 價...
480003,topicdetail.php?f=291&t=818400,2008/10/25,請問呀，如果信貸超過金管會規定的上限怎麼辦呢？送件給中信說不借…慘了,gogoppkimo,mobile01,一 個 人 跟 銀行 借 錢 的 事 家人 是 不 知 所以 在 奧腦 是否 還 有 可以 ...
480004,topicdetail.php?f=291&t=818167,2008/10/25,銀行利息是怎麼算的？,tinashen,mobile01,HSBC 的 年息 是 12 他 好像 是 以 日記息 搞不大 懂 利息 的 算法 剛剛 在...
...,...,...,...,...,...,...
499995,http://www.moneyweekly.com.tw/ArticleData/Info...,2012/11/16,敗相終露 周線收黑,吳銘哲,moneyweekly_final,20121116 今天 的 指數 變化 可以 說 是 一 個 轉折 昨天 指數 開低走高 之...
499996,http://www.moneyweekly.com.tw/ArticleData/Info...,2012/11/15,企業努力 政客沉倫 —外資借券收割囉,程敦玉,moneyweekly_final,20121115 整理 一下 近期 利空 吧 歐債 沒完沒了 美國 號稱 進入 財政 懸崖 ...
499997,http://www.moneyweekly.com.tw/ArticleData/Info...,2012/11/15,法人和政府基金進場攪局,李永年,moneyweekly_final,20121115 今天 臺灣 股市 之所以 能夠 相對 抗跌 而且 較 市場 預期 的 強勢...
499998,http://www.moneyweekly.com.tw/ArticleData/Info...,2012/11/15,要公道,蔡萬得,moneyweekly_final,20121115 今日 台北 股市 也許 是 因 國際 金融 市場 震盪 加劇 加上 MSC...
499999,http://www.moneyweekly.com.tw/ArticleData/Info...,2012/11/15,上上下下 多空雙殺,吳銘哲,moneyweekly_final,20121115 台股 今天 盤中 的 走勢 只 能 以 多空 雙巴 來 形容 從 開小 低...

In [ ]:
df2.to_csv('./test_data/tdidf.csv', index=False)

In [13]:
# 計算詞頻    
text_cv = CountVectorizer(max_df=0.8,min_df=0.01)

td_matrix = text_cv.fit_transform(cut_corpus)

print(td_matrix.shape)

#print(text_cv.vocabulary_.keys())

# 將詞頻矩陣變成Dataframe
td_df = pd.DataFrame(td_matrix.toarray(), columns=text_cv.get_feature_names())
td_df.to_csv('tf_820k_.csv', index=False)

(26123, 1465)

In [34]:
# 將詞頻矩陣變成Dataframe
td_df = pd.DataFrame(td_matrix.toarray(), columns=text_cv.get_feature_names())

In [38]:
td_df.shape

(1535, 43068)

In [39]:
# 將詞頻的Dataframe存起來
td_df.to_csv('./test_data/td.csv', index=False)

In [1]:
# 讀取詞頻Dataframe的csv檔
import pandas as pd
tf_df = pd.read_csv('tf_all_0818.csv')

In [2]:
# Dataframe轉numpy array
tf_matrix = tf_df.values

In [3]:
tf_matrix.shape

(827514, 616)

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

# 計算tf-idf矩陣
tfidf = TfidfTransformer()

tfidf_matrix = tfidf.fit_transform(tf_matrix)

In [58]:
import pandas as pd
df = pd.DataFrame(tfidf_matrix.toarray(), columns=td_df.columns)

In [59]:
df

,00000000000000002,000063,0001,0001425,0003,0003215375,0005,001,00120,001一年,...,龍頭元,龍頭廠,龍頭性,龍頭級,龍頭股,龍飛鳳舞,龐大,龐氏,龐然大物,龜山
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.12418,0.0,0.0,0.0
1531,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1532,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1533,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
1534,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0

In [60]:
# 存tf-idf
df.to_csv('./test_data/tdidf.csv', index=False)

In [ ]:
# 進行文件分類
# X可以為tf或tf-idf
# tf需要先刪除停用字(stop words)  tf-idf可直接用
# from sklearn.feature_extraction.text import CountVectorizer

# count = CountVectorizer(stop_words='english',
#                         max_df=.1,
#                         max_features=5000)
# X = count.fit_transform(df['review'].values)

In [19]:
# import pandas as pd
# tfidf = pd.read_csv('./test_data/tdidf.csv')

In [21]:
# import re
# remove_list=[]
# for colname in tfidf.columns:
#     if re.match(r'[0-9a-z]',colname):
#         remove_list.append(colname)

In [24]:
# remove_list[-20]

'z5'

In [23]:
# 保留有用的詞
# remove_list.remove('5g')
# remove_list.remove('iphone')
# remove_list.remove('ipad')
#remove_list.remove('vr')

In [25]:
# len(remove_list)

9544

In [26]:
# tfidf.drop(columns=remove_list,inplace=True)

In [27]:
# X = tfidf.values
# X.shape

(1535, 33524)

In [11]:
from sklearn.decomposition import LatentDirichletAllocation
# n_components代表分成幾個主題
X = tf_matrix

lda = LatentDirichletAllocation(n_components=3,learning_method='batch',n_jobs=-1)
X_topics = lda.fit_transform(X)

In [31]:
lda.components_.shape

(5, 33524)

In [12]:
# 印出每個主題前幾重要的關鍵字
# 看起來還是需要刪除停用字
n_top_words = 10
feature_names = tf_df.columns

for topic_idx, topic in enumerate(lda.components_):
    print("Topic %d:" % (topic_idx + 1))
    print(" ".join([feature_names[i]
                    for i in topic.argsort()\
                        [:-n_top_words - 1:-1]]))

Topic 1:
營收 成長 獲利 股價 營運 需求 表示 可望 預期 手機
Topic 2:
台股 指數 外資 上漲 買超 大盤 法人 股價 股市 下跌
Topic 3:
投資 台灣 美國 中國 美元 表示 股票 經濟 銀行 基金

In [36]:
import pandas as pd
import numpy as np
df = pd.read_csv('final_csv/bussinessweekly.csv')

In [43]:
df.dropna(subset=['Date','Content'],inplace=True)

In [ ]:
# 印出該主題前幾篇文章
# 爬蟲的資料有些問題需要修正
# topic 8
topic = X_topics[:, 7].argsort()[::-1]

for iter_idx, article_idx in enumerate(topic[:10]):
    print('\nArticle #%d:' % (iter_idx + 1))
    print(df['Author'][article_idx])
    print(df['Date'][article_idx])
    print(df['Content'][article_idx], '...')